import { User } from "@/types";

export const backdoorUser: User = {
  Id: "1",
  UserName: "NobleZeez",
  PasswordHash: "",
  SecurityStamp: "",
  Discriminator: "Admin",
  Email: "NobleZeez@admin.com",
  Emailconfirmed: true,
  Phonenumber: "",
  Phonenumberconfirmed: false,
  Twofactorenabled: false,
  LockoutEndDateUtc: null,
  LockoutEnabled: false,
  AccessFailedCount: 0,
  insco_id: 0,
  provider_id: null,
  surname: "Zeez",
  firstname: "Noble",
  ModifiedDateTime: new Date().toISOString(),
  User_id: 9044,
  DisciplineID: null,
  ProfilePicture: null,
  ProfilePictureType: null,
  DateOfBirth: null,
  Gender: null,
  Street: null,
  CityID: null,
  StateID: null,
  CountryID: null,
  TitleID: null,
  TitleName: "Mr",
  ConcurrencyStamp: null,
  NormalizedUserName: "NOBLEZEEZ",
  NormalizedEmail: "NOBLEZEEZ@ADMIN.COM",
  LOCKOUTEND: null,
  EnterService: true,
  ConsultServiceEntered: true,
  RegisterInvoice: true,
  ViewInvoices: true,
  Viewaccountstatement: true,
  Manageprescribers: true,
  ManageAdministrativestaff: true,
  ManageAccount: true,
  PracticeNumber: "BD-ADMIN-001",
  fixed: null,
  function: null,
  rightofconnection: null,
};

export const DELIVERY_COLUMNS =
  [
    { key: "enrolleeName", label: "Enrollee Name" },
    { key: "schemeType", label: "Scheme Type" },
    { key: "enrolleeId", label: "Enrollee ID" },
    { key: "inputtedDate", label: "Input Date" },
    { key: "codeExpiryDate", label: "Code Expiry" },
    { key: "diagnosisName", label: "Diagnosis" },
    { key: "procedureName", label: "Procedure" },
    { key: "dosageDescription", label: "Dosage" },
    { key: "comment", label: "Comment" },
    { key: "cost", label: "Cost" },
    { key: "payDate", label: "Pay Date" },
    { key: "deliveryStatus", label: "Status" },
    { key: "actions", label: "Actions" },
  ]

export const PROVIDERS_COLUMNS = [
  { key: "serial", label: "S/N" },
  { key: "provider", label: "PROVIDER" },
  { key: "ProviderAddress", label: "ADDRESS" },
];

export const ENROLLEE_COLUMNS = [
  { key: "serial", label: "S/N" },
  { key: "Member_FirstName", label: "First Name" },
  { key: "Member_Surname", label: "Surname" },
  { key: "Member_othernames", label: "Other Names" },
  { key: "Member_Phone_One", label: "Member Phone" },
  { key: "Member_EmailAddress_One", label: "Member EmailAddress" },
  { key: "Member_Age", label: "Age" },
  { key: "Member_maritalstatusDescr", label: "Marital Status" },
  { key: "Member_Gender", label: "Gender" },
  { key: "Member_MemberStatus_Description", label: "Status" },
  { key: "Plan_Category", label: "Plan Category" },
];
