import { User } from "@/types";

export const backdoorUser: User = {
  Id: "1",
  UserName: "NobleZeez",
  PasswordHash: "",
  SecurityStamp: "",
  Discriminator: "Admin",
  Email: "NobleZeez@admin.com",
  Emailconfirmed: true,
  Phonenumber: "",
  Phonenumberconfirmed: false,
  Twofactorenabled: false,
  LockoutEndDateUtc: null,
  LockoutEnabled: false,
  AccessFailedCount: 0,
  insco_id: 0,
  provider_id: null,
  surname: "Zeez",
  firstname: "Noble",
  ModifiedDateTime: new Date().toISOString(),
  User_id: 9044,
  DisciplineID: null,
  ProfilePicture: null,
  ProfilePictureType: null,
  DateOfBirth: null,
  Gender: null,
  Street: null,
  CityID: null,
  StateID: null,
  CountryID: null,
  TitleID: null,
  TitleName: "Mr",
  ConcurrencyStamp: null,
  NormalizedUserName: "NOBLEZEEZ",
  NormalizedEmail: "NOBLEZEEZ@ADMIN.COM",
  LOCKOUTEND: null,
  EnterService: true,
  ConsultServiceEntered: true,
  RegisterInvoice: true,
  ViewInvoices: true,
  Viewaccountstatement: true,
  Manageprescribers: true,
  ManageAdministrativestaff: true,
  ManageAccount: true,
  PracticeNumber: "BD-ADMIN-001",
  fixed: null,
  function: null,
  rightofconnection: null,
};
